app/BP_home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, IntegerField
from app.models import User
from wtforms.validators import DataRequired, EqualTo


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField("Current Password *", validators=[DataRequired()])
    new_password = PasswordField("New Password *", validators=[DataRequired()])
    confirm_new_password = PasswordField(
        "Confirm New Password *",
        validators=[DataRequired(), EqualTo("new_password")],
        render_kw={"onblur": "validatePassword()"},
    )
    submit = SubmitField("CHANGE PASSWORD")

app/BP_home/__init__.py
from flask import Blueprint

BP_home = Blueprint(
    'BP_home', __name__,
    template_folder='templates',
    static_folder='assets',
    static_url_path='/BP_home/assets'
)

app/BP_home/routes.py
from app.BP_home import BP_home
from app.BP_home.home_constants import HomeConstants, ServicesConstants
from app.models import Catalogue, Service, ProjectImage, Review, Location
from flask.templating import render_template

@BP_home.route("/")
def home():
    catalogue = Catalogue.query.order_by(Catalogue.start_price).all()
    showcase_images = ProjectImage.query.order_by(ProjectImage.date).limit(6).all()
    reviews = Review.query.filter(Review.status!="REMOVED").order_by(Review.date.desc()).all()
    location = Location.query.first()
    return render_template(
        "home.html",
        title="Home",
        showcase=showcase_images,
        services=catalogue,
        reviews=reviews,
        location=location,
        labels=HomeConstants.labels,
    )


@BP_home.route("/services")
def service_list():
    catalogue = Catalogue.query.all()
    return render_template(
        "services.html",
        title="Services",
        catalogue=catalogue,
        labels=ServicesConstants.labels,
    )


@BP_home.route("/blog")
def blog():
    return render_template("blog.html", title="Blog")

    

app/BP_home/templates/blog.html
{% extends 'main.layout.html' %}
{% set active='blog' %}

{% block page_style%}
<link rel="stylesheet" href="{{url_for('BP_home.static', filename='styles/BP_home.css')}}">
<link rel="stylesheet" href="{{url_for('BP_home.static', filename='styles/lightbox.min.css')}}">
{% endblock page_style %}

{% block body_content %}
<div class="blog-page">
    <div class="blog-header">
        <div class="header-content d-flex">
            <img src="{{url_for('BP_home.static', filename='images/asset-3.png')}}" alt="" class="header-img mb-4">
            <p class="h2 font-weight-bold text-dark text-uppercase text-center">our Journey So far</p>
            <a href="#first" class="text-decoration-none text-dark">
                <i class="fas fa-4x fa-arrow-circle-down"></i>
            </a>
        </div>
        <div class="sub-header container text-center d-flex justify-content-center">
            <p class="font-italic text-light text-center">Here is some of the latest stuff we've been working
                on.<br>Have a look at the
                best of KreatiVision. . .</p>
        </div>
    </div>
    <div class="container" id="blogItems">
        <div class="blog-layout row" id="first">
            <div class="text-container col-md-6 px-2">
                <p class="h2 text-warning">Design Type 1</p>
                <p class="font-italic text-light">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut maiores aspernatur officiis totam quis
                    asperiores minus sapiente?
                </p>
            </div>
            <div class="col-md-6 px-2">
                <div class="masonry">
                    <a href="{{url_for('static', filename='images/project-images/random-3.jpg')}}" class="grid"
                        data-lightbox="set1" data-title="Image part 1">
                        <img src="{{url_for('static', filename='images/project-images/random-3.jpg')}}">
                    </a>
                    <a href="{{url_for('static', filename='images/project-images/random-10.jpg')}}" class="grid"
                        data-lightbox="set1" data-title="Image checking 2">
                        <img src="{{url_for('static', filename='images/project-images/random-10.jpg')}}">
                    </a>
                    <a href="{{url_for('static', filename='images/project-images/random-7.jpg')}}" class="grid"
                        data-lightbox="set1" data-title="Image checking 3">
                        <img src="{{url_for('static', filename='images/project-images/random-7.jpg')}}">
                    </a>
                    <a href="{{url_for('static', filename='images/project-images/random-5.jpg')}}" class="grid"
                        data-lightbox="set1" data-title="Image got you here">
                        <img src="{{url_for('static', filename='images/project-images/random-5.jpg')}}">
                    </a>
                    <a href="{{url_for('static', filename='images/project-images/random-8.jpg')}}" class="grid"
                        data-lightbox="set1" data-title="Image finally someone did this more text more text more text more text more text more te">
                        <img src="{{url_for('static', filename='images/project-images/random-8.jpg')}}">
                    </a>
                    <a href="{{url_for('static', filename='images/project-images/random-12.jpg')}}" class="grid"
                        data-lightbox="set1" data-title="Image this one is last">
                        <img src="{{url_for('static', filename='images/project-images/random-12.jpg')}}">
                    </a>
                </div>
                <p class="small font-italic text-light text-center">Click on any image to open gallery.</p>
            </div>
        </div>
    </div>
    {% include 'fab.html' %}
    <!-- https://source.unsplash.com/random/6 -->
    <!-- LIGHTBOX: https://lokeshdhakar.com/projects/lightbox2/ -->
</div>
{% endblock body_content %}

{% block page_scripts %}
<script src=" {{url_for('BP_home.static', filename='js/home.js')}} "></script>
<script src=" {{url_for('BP_home.static', filename='js/lightbox.min.js')}} "></script>
<!-- LightBox Config -->
<script>
    lightbox.option({
        'resizeDuration': 450,
        'alwaysShowNavOnTouchDevices': true,
        'fadeDuration': 450,
        'imageFadeDuration': 450
    })
</script>
{% endblock page_scripts%}

app/BP_home/templates/home-old.html
{% extends 'main.layout.html' %}
{% set active='home' %}

{% block page_style%}
<link rel="stylesheet" href="{{url_for('BP_home.static', filename='styles/BP_home.css')}}">
{% endblock page_style %}

{% block body_content %}
<div class="home-sections">
  {#
  <!-- offer card | commeted-->
  {% if not current_user.admin %}
  <section id="offers" class="card shadow border-0 show">
    <div class="card-header border-0 d-flex justify-content-between pr-2">
      <h5 class="card-title">Launch Offer</h5>
      <button class="btn btn-sm ml-auto" onclick="dismissOffer()">
        <i class="fas fa-times"></i>
      </button>
    </div>
    <div class="card-body">
      <p class="h6">Get your designs created at upto <span class="display-4">50% off.</span></p>
      <small class="float-right"><a href="" class="text-secondary font-italic">{{labels['tncs']}}</a></small>
    </div>
    <div class="card-footer border-0">
      <a href="#services" class="btn btn-sm bg-dark text-warning shadow text-uppercase">
        {{labels['offerCTA']}} <i class="fas fa-chevron-right ml-2"></i>
      </a>
    </div>
  </section>
  {% endif %}
  #}

  <section id="site-intro">
    <div class="container">
      <div class="row pt-5">
        <div class="col-md-6 col-lg-6 d-flex flex-column justify-content-center intro-content">
          <!-- image displayed on handsets only. -->
          <div class="artwork position-absolute w-100">
            <img src="{{url_for('BP_home.static', filename='images/intro-art.svg')}}" alt="">
          </div>
          <div class="content position-absolute">
            <h3 class="font-weight-normal text-light" id="welcomeLabel">Welcome to</h3>
            <h1 class="text-uppercase text-warning" id="brand">kreativision photoarts</h1>
            <h5 class="text-info pb-3 border-bottom " id="tagline">Let's add the creativity to your brilliant vision. .
              .</h5>
            <p class="text-light font-italic" id="about">
              We are a freelancing group of creative individuals aimed at providing creative designing solutions to all
              kinds
              of small to large businesses.
              With a firm belief that reaching your audience the right way is the key to a steady growth, we help your
              business by providing graphic design solutions that do just that.
            </p>
            <div class="links-container d-flex justify-content-start mt-3">
              <a href="#services" class="btn btn-sm  font-weight-bold btn-warning mb-3 mr-3">
                {{labels['exploreServicesCTA']}}
                <span><i class="fas fa-chevron-right ml-2"></i></span>
              </a>
              <a href="#projects" class="btn btn-sm  font-weight-bold mb-3 text-warning pl-0">
                {{labels['recentProjectsCTA']}}
                <span><i class="fas fa-chevron-right ml-2"></i></span>
              </a>
            </div>
          </div>
        </div>
        <!-- image display on desktops -->
        <div class="col-md-6 col-lg-6 artwork-container d-flex align-items-center">
          <img src="{{url_for('BP_home.static', filename='images/intro-art.svg')}}" alt="">
        </div>
      </div>
    </div>
  </section>
  <!-- Popular Services Gallery -->
  <div class="section-head sec-5" id="services">
    <p class="h3 font-weight-light text-center text-light mb-4">{{labels['servicesHead']}}</p>
  </div>
  <section id="serviceGallery">
    <div class="row px-4">
      {% for service in services %}
      <div class="col-md-4 col-sm-12 col-lg-4">
        <div class="card bg-black-glass text-white text-center my-3">
          <div class="card-header border-0">
            <h4 class="card-title">{{service.name}}</h4>
          </div>
          <div class="card-body">
            <p class="card-text">{{service.description}}</p>
            <p class="h3">Starting @ just</p>
            <p class="display-3"><sup class="h2">₹</sup> {{service.start_price}}/-</p>
          </div>
          <div class="card-footer border-0">
            <a href="{{url_for('BP_home.service_list', _anchor=service.id)}}"
              class="btn btn-sm btn-light font-weight-bold text-uppercase">
              Explore <i class="fas fa-chevron-right ml-2"></i>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="container d-flex justify-content-center text-center mt-3">
      <a href="{{url_for('BP_home.service_list')}}" class="btn btn-sm btn-warning text-uppercase font-weight-bold shadow">
        {{labels['allServicesCTA']}} <i class="fas fa-chevron-right ml-2"></i>
      </a>
    </div>
  </section>

  <!-- Projects Gallery -->
  <div class="section-head" id="projects">
    <p class="h3 font-weight-light text-center text-light mb-4">What's going on lately!</p>
  </div>
  <section class="pb-3 w-100 project-gallery">
    <div class="row no-gutters">
      {% for image in showcase %}
      <div class="col-md-4 col-sm-6 gallery-item position-relative">
        <img src="{{url_for('static', filename='images/project-images/'+image.filepath)}}" alt=""
          class="w-100 h-100 position-absolute">
        <div class="about position-absolute w-100">
          <div class="title pl-2">
            <p class="h4 text-light">{{image.image_title}}</p>
            <small class="subtitle text-light font-italic">{{image.catalogue_name}} on {{image.date.strftime('%d, %m,
              %Y')}}</small>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="container-fluid text-center mt-4">
      <a href="{{url_for('BP_home.blog')}}" class="btn btn-sm btn-outline-warning font-weight-bold shadow">
        {{labels['allProjectsCTA']}} <i class="fas fa-chevron-right ml-2"></i>
      </a>
    </div>
  </section>

  <!-- Recent Reviews -->
  <div class="section-head" id="reviews">
    <p class="h3 font-weight-light text-center text-light mb-4">{{labels['reviewHead']}}</p>
  </div>
  <section id="reviewGallery">
    <div class="container mb-4">
      <div class="card-columns">
        {% for review in reviews %}
        <div class="card shadow rev border-0 review-{{loop.index0%4}}">
          <div class="card-header border-0">
            <h5 class="card-title mb-1">{{review.title}}</h5>
            <small class="card-subtitle font-weight-normal">By {{review.author}}</small>
          </div>
          {% if review.content %}
          <div class="card-body">
            <p class="card-tex">{{review.content}}</p>
          </div>
          {% endif %}
          <div class="card-footer border-0 d-flex justify-content-between">
            <small class="font-italic font-weight-bold service">For {{review.catalogue}}</small>
            <small class="font-italic">Posted on {{review.date.strftime('%B %d, %Y')}}</small>
          </div>
        </div>
        {% endfor %}
        <!-- Write a review button. -->
        {% if current_user.is_authenticated %}
        <div class="card shadow rev border-0 review-3">
          <div class="card-body d-flex justify-content-center">
            <a href="#" class="btn btn-sm btn-outline-warning shadow mx-auto font-weight-bold">
              ADD A REVIEW <i class="fas fa-chevron-right ml-2"></i>
            </a>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="d-flex get-started">
      <p class="h3 font-weight-normal text-light mb-3">Ready to get started?</p>
      <a href="{{url_for('BP_home.service_list')}}" class="btn btn-primary shadow border-0 text-uppercase">
        Let's make a design <i class="fas fa-chevron-right ml-3"></i>
      </a>
    </div>
  </section>

  <!-- Insert Footer Here -->
  {% include 'fab.html' %}
</div>
{% endblock body_content %}

{% block page_scripts %}
<script src=" {{url_for('BP_home.static', filename='js/home.js')}} "></script>
{% endblock page_scripts%}

app/BP_home/templates/home.html
{% extends 'main.layout.html' %}
{% set active='home' %}

{% block page_style%}
<link rel="stylesheet" href="{{url_for('BP_home.static', filename='styles/BP_home.css')}}">
{% endblock page_style %}

{% block body_content %}
<div class="home-page">
    <section class="header px-1">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-6 d-flex flex-column justify-content-center primary-column">
                    <p class="display-4">Designing stuff that <br>Shines You</p>
                    <h3 class="text-uppercase">at kreativision photoarts</h3>
                    <p class="font-italic">We create designs that reflect your brilliant visions in the best way
                        possible.</p>
                    <p class="mt-3 font-italic">Let's build something wonderful together!</p>
                    <div class="mt-4 row">
                        <div class="col-md-5 col-lg-5">
                            <a href="#services" class="btn btn-sm font-weight-bold mb-3 shadow primary-cta">
                                {{labels['exploreServicesCTA']}}
                                <span class="ml-2 fas fa-chevron-right"></span>
                            </a>
                        </div>
                        <div class="col-md-7 col-lg-7">
                            <a href="#projects" class="btn btn-sm font-weight-bold mb-3 pl-0 text-light">
                                {{labels['recentProjectsCTA']}}
                                <span class="ml-2 fas fa-chevron-right"></span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6 primary-column artwork">
                    <img src="{{url_for('BP_home.static', filename='images/intro-art.svg')}}" alt="">
                </div>
            </div>
        </div>
    </section>

    <section class="services px-1" id="services">
        <div class="container">
            <h3 class="text-center text-dark section-head">Our Top Services</h3>
            <div class="row">
                {% for service in services %}
                <div class="col-md-4 col-lg-4">
                    <div class="card card-body border-0 bg-light text-dark text-center my-3">
                        <div class="content">
                            <h5 class="card-title">{{service.name}}</h5>
                            <p class="card-text mt-2">{{service.description}}</p>
                            <p class="font-italic mt-4 small text-primary">Starting @ just</p>
                            <h3><sup><i class="small fas fa-rupee-sign mr-1"></i></sup><span class="font-italic">{{service.start_price}}</span></h3>
                        </div>
                        <a href="{{url_for('BP_home.service_list', _anchor=service.id)}}"
                            class="btn mt-4 btn-sm btn-warning shadow font-weight-bold text-uppercase mx-auto">
                            Explore
                            <i class="fas fa-chevron-right ml-2"></i>
                        </a>
                    </div>
                </div>
                {% endfor %}
                <div class="container d-flex justify-content-center text-center mt-3 mb-4">
                    <a href="{{url_for('BP_home.service_list')}}" class="btn btn-sm btn-dark text-uppercase shadow">
                        {{labels['allServicesCTA']}} <i class="fas fa-chevron-right ml-2"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section class="projects mt-4" id="projects">
        <h3 class="text-center text-light mb-4 section-head">Latest Projects</h3>
        <div class="row no-gutters">
            {% for image in showcase %}
            <div class="col-md-4 col-sm-6 gallery-item position-relative">
                <img src="{{url_for('static', filename='images/project-images/'+image.filepath)}}" alt=""
                    class="w-100 h-100 position-absolute">
                <div class="about position-absolute w-100">
                    <div class="title pl-2">
                        <p class="h4 text-light">{{image.image_title}}</p>
                        <small class="subtitle text-light font-italic">
                            {{image.catalogue_name}} on {{image.date.strftime("%d, %m, %Y")}}
                        </small>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="container-fluid text-center py-4">
                <a href="{{url_for('BP_home.blog')}}" class="btn btn-sm btn-warning font-weight-bold shadow">
                    {{labels['allProjectsCTA']}} <i class="fas fa-chevron-right ml-2"></i>
                </a>
            </div>
        </div>
    </section>

    <section class="reviews px-1 py-4">
        <h3 class="text-center text-dark mb-4">What Our Clients Say</h3>
        <div class="container">
            <div class="card-columns">
                {% for review in reviews %}
                <div class="card shadow rev border-0">
                    <div class="card-header border-0">
                        <h5 class="card-title mb-1">{{review.title}}</h5>
                        <small class="card-subtitle font-weight-normal">By {{review.author}}</small>
                    </div>
                    {% if review.content %}
                    <div class="card-body">
                        <p class="card-tex">{{review.content}}</p>
                    </div>
                    {% endif %}
                    <div class="card-footer border-0 d-flex justify-content-between">
                        <small class="font-italic font-weight-bold service">For {{review.catalogue}}</small>
                        <small class="font-italic">Posted on {{review.date.strftime('%B %d, %Y')}}</small>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <section class="team px-1 py-4">
        <h3 class="text-center text-light mb-4">Meet Our Team</h3>
        <div class="container px-1">
            <div class="row">
                <div class="col-md-6 col-lg-6">
                    <div class="card card-body border-0 mb-3 shadow px-2 d-flex flex-row justify-content-start">
                        <div class="img-container shadow mr-3">
                            <img src="https://source.unsplash.com/random/120x120" alt="">
                        </div>
                        <div class="info-container d-flex flex-column justify-content-center">
                            <h4 class="font-italic">Amittras Pal</h4>
                            <small class="font-italic">Designer</small>
                            <div class="contact mt-3 d-flex">
                                <a href="#" class="btn btn-sm shadow btn-primary border-0 rounded-circle mr-3">
                                    <i class="fab fa-facebook"></i>
                                </a>
                                <a href="#" class="btn btn-sm shadow btn-success border-0 rounded-circle mr-3">
                                    <i class="fab fa-whatsapp"></i>
                                </a>
                                <a href="#" class="btn btn-sm shadow btn-info border-0 rounded-circle mr-3">
                                    <i class="fab fa-instagram"></i>
                                </a>
                                <a href="#" class="btn btn-sm shadow btn-danger border-0 rounded-circle mr-3">
                                    <i class="fas fa-envelope"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6">
                    <div class="card card-body border-0 mb-3 shadow px-2 d-flex flex-row justify-content-start">
                        <div class="img-container shadow mr-3">
                            <img src="https://source.unsplash.com/random/120x120" alt="">
                        </div>
                        <div class="info-container d-flex flex-column justify-content-center">
                            <h4 class="font-italic">Sukriti Shukla</h4>
                            <small class="font-italic">Consultant</small>
                            <div class="contact mt-3 d-flex">
                                <a href="#" class="btn btn-sm shadow btn-primary border-0 rounded-circle mr-3">
                                    <i class="fab fa-facebook"></i>
                                </a>
                                <a href="#" class="btn btn-sm shadow btn-success border-0 rounded-circle mr-3">
                                    <i class="fab fa-whatsapp"></i>
                                </a>
                                <a href="#" class="btn btn-sm shadow btn-info border-0 rounded-circle mr-3">
                                    <i class="fab fa-instagram"></i>
                                </a>
                                <a href="#" class="btn btn-sm shadow btn-danger border-0 rounded-circle mr-3">
                                    <i class="fas fa-envelope"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="contact bg-dark pt-4">
        <h3 class="text-center text-light mb-4">Get In Touch</h3>
        <div class="container">
            <h5 class="text-light">We are in {{location.city}}.</h5>
            <iframe class="w-100 shadow rounded" src="{{location.map_link}}" style="border:0; height: 256px;" allowfullscreen=""
                loading="lazy"></iframe>
            <div class="row mt-4">
                <div class="col-md-4 col-lg-4 d-flex flex-column">
                    <h5 class="text-light py-3">Contact Us:</h5>
                    <a href="#" class="text-warning mb-3 text-decoration-none">
                        <i class="fab fa-whatsapp mr-2"></i>WhatsApp
                    </a>
                    <a href="#" class="text-warning mb-3 text-decoration-none">
                        <i class="fas fa-envelope mr-2"></i>GMail
                    </a>
                    <a href="#" class="text-warning mb-3 text-decoration-none">
                        <i class="fab fa-instagram mr-2"></i>Instagram
                    </a>
                </div>
                <div class="col-md-4 col-lg-4 d-flex flex-column">
                    <h5 class="text-light py-3">About Us:</h5>
                    <a href="#" class="text-warning mb-3 text-decoration-none">
                        <i class="fas fa-blog mr-2"></i>KreatiVision Blog
                    </a>
                    <a href="#" class="text-warning mb-3 text-decoration-none">
                        <i class="fas fa-file-contract mr-2"></i>Terms of Service
                    </a>
                </div>
            </div>
        </div>
        <div class="container-fluid copyrights py-3">
            <p class="text-center text-light">KreatiVision Photoarts &#169; 2021</p>
        </div>
    </section>
</div>
{% endblock body_content %}

app/BP_home/templates/macros.html
{% macro project(project_name='', service_name='', description='', img_url='', img_file='') -%}
<div class="project">
    <a href="#">
        <img src="{{url_for(img_url, filename=img_file)}}" alt="" class="col-backdrop">
    </a>
    <div class="content px-3 text-center bg-black-glass shadow">
        <p class="h3 text-white">{{project_name}}</p>
        <p class="text-white font-italic font-weight-light">{{service_name}}</p>
        <p class="text-light fot-weight-light text-left">
            {{description}}
        </p>
        <a href="#" class="links d-flex mx-auto align-items-center">
            <span class="text-warning mb-1">Read More</span>
            <span class="btn btn-sm btn-warning shadow ml-2 text-center">
                <i class="fas fa-chevron-right"></i>
            </span>
        </a>
    </div>
</div>
{%- endmacro %}

app/BP_home/templates/services.html
{% extends 'main.layout.html' %}
{% set active='services' %}

{% block page_style%}
<link rel="stylesheet" href="{{url_for('BP_home.static', filename='styles/BP_home.css')}}">
{% endblock page_style %}

{% block body_content %}
<p class="container h2 text-center text-light section-head">{{labels['heading']}}</p>
<section class="mb-5 service-list">
    {% for item in catalogue %}
    <div class="container-fluid px-2" id="{{item.id + 'Parent'}}">
        <div class="container review-2 shadow service-name my-2 rounded">
            <div class="content d-flex">
                <p class="h4 w-50 my-4">{{item.name}}</p>
                <a class="ml-auto mr-2 btn btn-sm btn-light border-0 shadow" onclick="scrollCollapseToView(this)"
                    id="btn-{{item.id}}" data-toggle="collapse" aria-controls="{{item.id}}" aria-expanded="false">
                    <span class="font-weight-bold">EXPLORE</span> <i class="fas fa-chevron-down ml-1"></i>
                </a>
            </div>
            <div class="collapse container px-0 py-0" id="{{item.id}}">
                <div class="row">
                    {% for service in item.variations %}
                    <div class="col-md-4 col-lg-4 mb-3">
                        <div class="card shadow border-0 rounded">
                            <img src="{{url_for('static', filename='images/service-images/'+service.header_img)}}" alt="" class="card-img-top">
                            <div class="card-body text-center pb-0 px-2">
                                <!-- <h5 class="card-title">{{service.name}}</h5> -->
                                <p class="small card-text mb-2">{{service.description}}</p>
                                <p class="h5 text-info">{{labels['getYours']}}</p>
                                <p class="h3">
                                    <sup class="h5"><i class="small fas fa-rupee-sign mr-1"></i> </sup>{{service.price}}/-
                                </p>
                            </div>
                            <div class="card-footer border-0 d-flex justify-content-center">
                                <a href="{{url_for('BP_account.customize_service', service_Id=service.id)}}" class="btn btn-sm btn-warning border-0 shadow font-weight-bold">
                                    {{labels['makeThis']}} <i class="fas fa-chevron-right ml-2"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="container-fluid px-2" id="contactUs">
        <div class="container review-0 shadow service-name my-2 rounded">
            <div class="content d-flex">
                <p class="h4 w-50 my-4">Need something different?</p>
                <a href="#" class="ml-auto mr-2 btn btn-sm btn-dark border-0 shadow">
                    <span class="font-weight-bold text-uppercase">Contact US</span>
                </a>
            </div>
        </div>
    </div>
</section>

{% include 'fab.html' %}
{% endblock body_content %}

{% block page_scripts %}
<script src="{{url_for('BP_home.static', filename='js/home.js')}}"></script>
{% endblock page_scripts%}

app/BP_home/templates/test.html
{% extends 'main.layout.html' %}
{% set active='blog' %}

{% block page_style%}
<link rel="stylesheet" href="{{url_for('BP_home.static', filename='styles/BP_home.css')}}">
{% endblock page_style %}

{% block body_content %}
<!-- <div style="padding-top: 60px;" class="mt-3 ml-5">
    <button type="button" class="btn btn-light font-weight-bold" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        <i class="fas fa-pencil-alt mr-2"></i> EDIT
    </button>
    <div class="dropdown-menu">
        <button class="dropdown-item" href="#">Profile</button>
        <button class="dropdown-item" href="#" data-toggle="modal" data-target="#editPassword">Password</button>
    </div>
</div> -->
<div class="card ml-5 mt-5" style="width: 18rem;">
    <div class="card-header d-flex justify-content-center">
        <img src="{{url_for('static', filename='images/project-images/random-1.jpg')}}" alt="" style="width: 150px; height: 150px; border-radius: 50%;" class="mt-3">
    </div>
</div>
{% endblock body_content %}

{% block page_scripts %}
<script src=" {{url_for('BP_home.static', filename='js/home.js')}} "></script>
{% endblock page_scripts%}