app/BP_admin/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.core import StringField
from wtforms.validators import DataRequired, Optional
from wtforms.fields.simple import SubmitField, TextAreaField


class EditReviewForm(FlaskForm):
    review_title = StringField(
        "Review Title *", validators=[DataRequired()], render_kw={"maxlength": "140"}
    )
    review_content = TextAreaField("Review Content", validators=[Optional()], render_kw={"rows": "8"})
    submit_review = SubmitField("Save")

class LocationForm(FlaskForm):
    city = StringField("City, State *", validators=[DataRequired()])
    map_link = StringField("Google Maps Embed Link *", validators=[DataRequired()])
    update = SubmitField("SAVE")

app/BP_admin/__init__.py
from flask import Blueprint

BP_admin = Blueprint(
    "BP_admin",
    __name__,
    template_folder="templates",
    static_folder="assets",
    static_url_path="/BP_admin/assets",
)

app/BP_admin/routes.py
from app import db
import app.utils as utils
from app.models import Review, ReviewSchema, Location
from app.decorators import admin_required
from app.BP_admin import BP_admin
from app.BP_admin.forms import EditReviewForm, LocationForm
from app.global_forms import (
    UpdateAccountInfoForm,
    ChangeUserPasswordForm,
    UpdateDPForm,
    prefix,
)
from flask import flash, redirect, request, url_for
from flask.templating import render_template
from flask_login import login_required


@BP_admin.route("/a/reviews")
@login_required
@admin_required
def reviews():
    edit_review_form = EditReviewForm()
    return render_template(
        "reviews.html", title="Manage Reviews", editForm=edit_review_form
    )


@BP_admin.route("/a/dashboard")
@login_required
@admin_required
def home():
    return render_template("dashboard.html", title="Dashboard")


@BP_admin.route("/a/order/<string:id>")
@login_required
@admin_required
def order_id(id):
    return render_template("order-details.html")


@BP_admin.route("/a/orders/<string:status>")
@login_required
@admin_required
def order_type(status):
    return render_template("orders.html")


@BP_admin.route("/a/services")
@login_required
@admin_required
def services():
    return render_template("admin-services.html", title="Manage Services")


@BP_admin.route("/a/blog")
@login_required
@admin_required
def blog():
    return render_template("admin-blog.html", title="Manage Blog")


@BP_admin.route("/a/offers")
@login_required
@admin_required
def offers():
    return render_template("offers.html", title="Manage Offers")


@BP_admin.route("/a/settings", methods=["GET", "POST"])
@login_required
@admin_required
def settings():
    edit_form = UpdateAccountInfoForm(prefix=prefix["info"])
    change_pwd_form = ChangeUserPasswordForm(prefix=prefix["pwd"])
    dp_form = UpdateDPForm(prefix=prefix["dp"])
    locationForm = LocationForm(prefix="loc")
    loc = Location.query.first()
    city = loc.city.split(" ")[0]
    city = city[:city.index(",")]
    if request.method == "POST" and request.form["form"] == "pwd":
        if change_pwd_form.validate_on_submit():
            utils.change_password(change_pwd_form.new_password.data)
            content = [f"Success", f"Your assword is updated."]
            flash(content, category="success")
            return redirect(url_for("BP_admin.settings"))
    elif request.method == "POST" and request.form["form"] == "info":
        if edit_form.validate_on_submit():
            utils.update_user(edit_form.data)
            content = [f"Success", f"Your details are updated."]
            flash(content, category="success")
            return redirect(url_for("BP_admin.settings"))
    elif request.method == "POST" and request.form["form"] == "dp":
        if dp_form.validate_on_submit():
            utils.update_dp(dp_form.dp_image.data)
            content = [f"Success", f"Your profile image is updated."]
            flash(content, category="success")
            return redirect(url_for("BP_admin.settings"))
    elif request.method == "POST" and request.form["form"] == "loc":
        if locationForm.validate_on_submit():
            loc.city = locationForm.city.data
            loc.map_link = locationForm.map_link.data
            db.session.commit()
            content = [f"Success", f"Location Data updates successfully"]
            flash(content, category="success")
            return redirect(url_for("BP_admin.settings"))
    return render_template(
        "settings.html",
        title="Admin Settings",
        detailsForm=edit_form,
        passwordForm=change_pwd_form,
        dpForm=dp_form,
        city=city,
        locationForm=locationForm,
    )

app/BP_admin/templates/admin-blog.html
{% extends 'admin.layout.html' %}
{% set active='blog' %}

{% block admin_content %}
<div class="container mt-3">
    <p class="h4">Manage the blog content</p>
</div>
{% endblock admin_content %}

app/BP_admin/templates/admin-services.html
{% extends 'admin.layout.html' %}
{% set active='services' %}

{% block admin_content %}
<div class="admin-services">
    <div class="container my-3 d-flex justify-content-between align-items-center">
        <h5 class="text-light m-0" id="viewMode">Service Catalogs</h5>
    </div>

    <div class="container services mt-3">
        <div class="row">
            <div class="col-md-4 col-lg-3">
                <div class="card border-0 mb-3 service-card">
                    <div class="card-header d-flex justify-content-between align-items-center border-0 pr-2">
                        <h5 class="card-title mb-0">Brochure Design</h5>
                        <!-- <div class="dropdown service-actions">
                            <button class="btn btn-sm ml-3" data-toggle="dropdown">
                                <i class="fas fa-ellipsis-v"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right shadow border-0">
                                <button class="dropdown-item">VIEW DETAILS</button>
                                <button class="dropdown-item">ADD SERVICE</button>
                            </div>
                        </div> -->
                    </div>
                    <div class="card-body pt-2">
                        <p class="card-text mb-2">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, est.</p>
                        <p class="card-text mb-2 font-italic">Services: <span class="text-primary">3</span></p>
                        <p class="card-text mb-2 font-italic">Starting Price: <span class="text-primary"><i class="small fas fa-rupee-sign mr-1"></i> 349/-</span></p>
                    </div>
                    <div class="card-footer bg-dark border-0">
                        <button class="btn btn-sm shadow btn-warning mr-2">
                            View Services
                        </button>
                        <button class="btn btn-sm shadow btn-secondary">
                            Edit
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-3">
                <a href="#" class="text-decoration-none">
                    <div class="card border-0 mb-3 add-new">
                        <div class="card-body d-flex flex-column justify-content-center align-items-center">
                            <div class="fa-stack fa-4x">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fas fa-plus fa-stack-1x fa-inverse iconoverlay"></i>
                            </div>
                            <h6 class="text-uppercase font-weight-bold mt-3">
                                ADD <span id="addType">CATALOGUE</span>
                            </h6>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock admin_content %}

{% block page_script %}
<script src="{{url_for('BP_admin.static', filename='js/services.js')}}"></script>
{% endblock %}

app/BP_admin/templates/admin.layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/vendors.css')}}">
    <link rel="stylesheet" href="{{url_for('BP_admin.static', filename='styles/admin.css')}}">
    <title>{{title}} | KV Admin</title>
</head>

<body>
    {% set navItems = [
    ('tachometer-alt', url_for('BP_admin.home'), 'dashboard', 'Dashboard'),
    ('tags', url_for('BP_admin.order_type', status='new'), 'orders', 'Orders'),
    ('comments', url_for('BP_admin.reviews'), 'reviews', 'Reviews'),
    ('boxes', url_for('BP_admin.services'), 'services', 'Services'),
    ('blog', url_for('BP_admin.blog'), 'blog', 'Blog'),
    ('shapes', url_for('BP_admin.offers'), 'offers', 'Offers'),
    ('cog', url_for('BP_admin.settings'), 'settings', 'Settings'),
    ('sign-out-alt', url_for('BP_auth.logout'), 'logout', 'Logout')
    ] %}
    {% set active = active|default('admin_home') -%}
    <header>
        <nav class="bg-dark" id="sidebar">
            <ul class="list-unstyled text-white">
                {% for icon, href, id, caption in navItems %}
                <li class="{{'active' if active==id else ''}}">
                    <a href="{{href|e}}" class="nav-link text-light d-flex align-items-center">
                        <i class="fas fa-{{icon}} mr-2"></i> {{caption|e}}<i
                            class="active-ico fas fa-chevron-right ml-auto mr-3"></i>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </nav>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark shadow">
            <button type="button" class="btn ml-0" id="sidebarToggle" onclick="toggleSidebar('open')">
                <i class="fas fa-stream text-white"></i>
            </button>
            <a class="navbar-brand mr-auto ml-2">KV PhotoArts: Admin</a>
        </nav>
    </header>
    <main class="content">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, content in messages %}
        <div class="toast shadow" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2300">
            <div class="toast-header">
                <strong class="mr-auto text-{{category}}">{{content[0]}}</strong>
            </div>
            <div class="toast-body">
                {{content[1]}}
            </div>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block admin_content %}{% endblock %}
    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <script src="{{url_for('BP_admin.static', filename='js/admin.js')}}"></script>
</body>

{% block page_script %}{% endblock %}
</html>

app/BP_admin/templates/dashboard.html
{% extends 'admin.layout.html' %}
{% set active='dashboard' %}

{% block admin_content %}
<div class="dashboard">
    <div class="container mt-2">
        <h5 class="text-light">Updates</h5>
        <div class="row updates">
            <div class="col-md-4 col-lg-4">
                <div class="card shadow border-0 mb-3">
                    <div class="card-body">
                        <h5 class="text-dark">4 new orders</h5>
                        <p class="text-muted">From XYZ, Someone and 2 others.</p>
                        <a href="#" class="btn btn-sm btn-warning shadow">
                            View &amp; Take Actions<i class="fas fa-chevron-right ml-2"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-4">
                <div class="card shadow border-0 mb-3">
                    <div class="card-body">
                        <h5 class="text-dark">3 new reviews</h5>
                        <p class="text-muted">From User 1, User 2 and 1 others.</p>
                        <a href="#" class="btn btn-sm btn-warning shadow">
                            View &amp; Take Actions <i class="fas fa-chevron-right ml-2"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-4">
                <div class="card shadow border-0 mb-3">
                    <div class="card-body">
                        <h5 class="text-dark">Sales this month: <span class="text-primary"><i class="small fas fa-rupee-sign mr-1"></i> 2368</span></h5>
                        <p class="text-success"><span class="font-weight-bold">+ <i class="small fas fa-rupee-sign mr-1"></i>259</span> from last month.</p>
                        <a href="#" class="btn btn-sm btn-warning shadow">
                            See Report <i class="fas fa-chevron-right ml-2"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mb-3">
        <h5 class="text-light">Orders in progress</h5>
        <div class="order-list shadow">
            <table class="table table-borderless table-hover bg-light">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Order ID</th>
                        <th scope="col">Owner</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr role="button" tabindex="0" id="order-1">
                        <td scope="row">120321:1754</td>
                        <td>User X</td>
                        <td>In Progress</td>
                    </tr>
                    <tr role="button" tabindex="0" id="order-2">
                        <td scope="row">110720:1209</td>
                        <td>Amittras</td>
                        <td>Pending Payment</td>
                    </tr>
                    <tr role="button" tabindex="0" id="order-3">
                        <td scope="row">060221:1604</td>
                        <td>Fireman</td>
                        <td>In Progress</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="container mb-3">
        <h5 class="text-light">Quick Actions</h5>
        <div class="row no-gutters shadow quick-actions">
            <div class="col-md-3 col-lg-3 action">
                <a href="" class="text-decoration-none text-dark">
                    <span class="d-flex flex-column align-items-center py-3">
                        <i class="fas fa-users"></i>
                        <p class="mb-0">Find a User</p>
                    </span>
                </a>
            </div>
            <div class="col-md-3 col-lg-3 action">
                <a href="" class="text-decoration-none text-dark">
                    <span class="d-flex flex-column align-items-center py-3">
                        <i class="fas fa-blog"></i>
                        <p class="mb-0">Add new blog entry</p>
                    </span>
                </a>
            </div>
            <div class="col-md-3 col-lg-3 action">
                <a href="" class="text-decoration-none text-dark">
                    <span class="d-flex flex-column align-items-center py-3">
                        <i class="fas fa-shapes"></i>
                        <p class="mb-0">Create new offer</p>
                    </span>
                </a>
            </div>
            <div class="col-md-3 col-lg-3 action">
                <a href="" class="text-decoration-none text-dark">
                    <span class="d-flex flex-column align-items-center py-3">
                        <i class="fas fa-boxes"></i>
                        <p class="mb-0">Add a new service</p>
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock admin_content %}

app/BP_admin/templates/offers.html
{% extends 'admin.layout.html' %}
{% set active='offers' %}

{% block admin_content %}
<div class="container mt-3">
    <p class="h4">Manager the offers on the site.</p>
</div>
{% endblock admin_content %}

app/BP_admin/templates/order-details.html
{% extends 'admin.layout.html' %}
{% set active='orders' %}

{% block admin_content %}
<div class="container my-3">
    <a href="{{url_for('BP_admin.order_type', status='new')}}" class="btn p-0 text-light">
        <i class="fas fa-arrow-left mr-1"></i> Back to orders list
    </a>
</div>
<div class="container my-2 order-details">
    <div class="card">
        <div class="card-header d-flex justify-content-between px-2 bg-white">
            <div class="details">
                <h5 class="card-title">Order ID: 00001111</h5>
                <p class="small mb-1 text-muted">Created: <span class="font-italic">Order Date</span></p>
                <p class="small mb-1 text-muted">Status: <span class="font-italic">Peding Payment</span></p>
                <p class="small mb-1 text-muted">
                    Owner: <span class="font-italic">
                        <a href="#clientInfoModal" class="font-italic text-decoration-none link"
                            data-toggle="modal">Client Name</a>
                    </span>
                </p>
            </div>
            <div class="actions d-flex flex-column justify-content-between">
                <div class="dropdown">
                    <button class="btn shadow-sm btn-success btn-sm" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-pen mr-2"></i>Update
                    </button>
                    <div class="dropdown-menu dropdown-menu-right bg-dark border-0"
                        aria-labelledby="dropdownMenuButton">
                        <button class="dropdown-item">Confirm</button>
                        <button class="dropdown-item">In Progress</button>
                        <button class="dropdown-item">Pendin Payment</button>
                        <button class="dropdown-item">Completed</button>
                    </div>
                </div>
                <button class="btn shadow-sm btn-info btn-sm"><i class="fas fa-upload mr-2"></i>Design</button>
                <button class="btn shadow-sm btn-secondary btn-sm"><i
                        class="fas fa-file-invoice mr-2"></i>Invoice</button>
            </div>
        </div>
        <div class="card-body py-0 px-2">
            <div class="card card-body my-3 bg-warning text-dark shadow border-0">
                <div class="card-text d-flex justify-content-between">
                    <p class="font-weight-bold"> Web Posters
                        <span class="ml-1 badge badge-pill badge-light" style="line-height: 24px;">3X </span>
                    </p>
                    <p class="h5"><i class="small fas fa-rupee-sign mr-1"></i> 747</p>
                </div>
            </div>
            <div class="card card-body my-3 bg-warning text-dark shadow border-0">
                <div class="card-text d-flex justify-content-between">
                    <p class="font-weight-bold">Brochure Design</p>
                    <p class="h5"><i class="small fas fa-rupee-sign mr-1"></i> 450</p>
                </div>
                <p class="small">Client has provided reference images for this item.</p>
                <div class="ref d-flex">
                    <button class="btn btn-sm btn-dark shadow mr-2" data-toggle="modal"
                        data-target="#referenceImages"><i class="fas fa-eye mr-1"></i> View</button>
                    <button class="btn btn-sm btn-outline-light"><i class="fas fa-download mr-1"></i> Download</button>
                </div>
            </div>
            <div class="card card-body my-3 bg-warning text-dark shadow border-0">
                <div class="card-text d-flex justify-content-between">
                    <p class="font-weight-bold">Print Media Design</p>
                    <p class="h5"><i class="small fas fa-rupee-sign mr-1"></i> 350</p>
                </div>
            </div>
        </div>
        <div class="card-footer d-flex justify-content-between px-2 pt-0 bg-white border-0">
            <h4 class=" mb-0 text-dark">Total Amount:</h4>
            <h4 class=" mb-0 text-primary"><i class="small fas fa-rupee-sign mr-1"></i> 1547/-</h4>
        </div>
    </div>
</div>


<div class="modal fade bg-clear-glass" id="referenceImages" tabindex="-1" role="dialog"
    aria-labelledby="referenceImagesLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content border-0">
            <div class="modal-header d-flex flex-column align-items-center border-warning">
                <h5 class="modal-title" id="referenceImagesLabel">Reference Images</h5>
            </div>
            <div class="modal-body">
                <div id="refImgCarousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="https://source.unsplash.com/random/6" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="https://source.unsplash.com/random/2" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="https://source.unsplash.com/random/1" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#refImgCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#refImgCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bg-clear-glass" id="clientInfoModal" tabindex="-1" role="dialog"
    aria-labelledby="clientInfoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content border-0">
            <div class="modal-header d-flex flex-column align-items-center border-warning">
                <h5 class="modal-title" id="clientInfoModalLabel">Client's Name</h5>
            </div>
            <div class="modal-body pb-4">
                <div class="d-flex justify-content-center">
                    <img src="https://source.unsplash.com/random/200x200" alt="" class="rounded-circle">
                </div>
                <div class="d-flex justify-content-center mt-4">
                    <a href="#" class="btn btn-sm mx-2 btn-light shadow">
                        <i class="fas fa-phone-alt mr-2"></i>Call
                    </a>
                    <a href="#" class="btn btn-sm mx-2 btn-success shadow">
                        <i class="fab fa-whatsapp mr-2"></i>Message
                    </a>
                    <a href="#" class="btn btn-sm mx-2 btn-warning shadow">
                        <i class="fas fa-envelope mr-2"></i>Mail
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock admin_content %}

{% block page_script %}
<!-- <script src="{{url_for('BP_admin.static', filename='js/orders.js')}}"></script> -->
{% endblock %}

app/BP_admin/templates/orders.html
{% extends 'admin.layout.html' %}
{% set active='orders' %}

{% block admin_content %}
<div class="orders-page">
  <!-- Header and Filter -->
  <div class="container my-3 d-flex justify-content-between">
    <h5 class="text-light m-0">Orders</h5>
    <div class="dropdown">
      <span class="text-dark font-weight-bold">Status:</span>
      <button class="btn btn-dark btn-sm dropdown-toggle shadow rounded" type="button" id="dropdownMenuButton"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        New Unconfirmed
      </button>
      <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="dropdownMenuButton">
        <button class="dropdown-item" onclick="loadOrders('new')">New Unconfirmed</button>
        <button class="dropdown-item" onclick="loadOrders('in progress')">In Progress</button>
        <button class="dropdown-item" onclick="loadOrders('pending payment')">Pending Payment</button>
        <button class="dropdown-item" onclick="loadOrders('completed')">Completed</button>
      </div>
    </div>
  </div>

  <!-- List -->
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-6">
        <div class="card card-body shadow bg-light border-0 my-2">
          <div class="row d-flex align-items-center">
            <div class="col-10">
              <h5>Order ID: 00001111</h5>
              <p class="small text-muted mb-1">
                <span class="font-weight-bold">Placed On:</span>
                <span class="font-italic">Order Date</span>
              </p>
              <p class="small mb-0 text-dark">
                <span class="text-primary font-weight-bold">Client:</span>
                <span class="text-primary font-italic">Order Owner</span>
              </p>
            </div>
            <div class="col-2 d-flex justify-content-center">
              <a href="{{url_for('BP_admin.order_id', id='01')}}" class="btn btn-outline-dark border-0 details-btn">
                <i class="fas fa-chevron-right"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-6">
        <div class="card card-body shadow bg-light border-0 my-2">
          <div class="row d-flex align-items-center">
            <div class="col-10">
              <h5>Order ID: 00001111</h5>
              <p class="small text-muted mb-1">
                <span class="font-weight-bold">Placed On:</span>
                <span class="font-italic">Order Date</span>
              </p>
              <p class="small mb-0 text-dark">
                <span class="text-primary font-weight-bold">Client:</span>
                <span class="text-primary font-italic">Order Owner</span>
              </p>
            </div>
            <div class="col-2 d-flex justify-content-center">
              <a href="{{url_for('BP_admin.order_id', id='01')}}" class="btn btn-outline-dark border-0 details-btn">
                <i class="fas fa-chevron-right"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-6">
        <div class="card card-body shadow bg-light border-0 my-2">
          <div class="row d-flex align-items-center">
            <div class="col-10">
              <h5>Order ID: 00001111</h5>
              <p class="small text-muted mb-1">
                <span class="font-weight-bold">Placed On:</span>
                <span class="font-italic">Order Date</span>
              </p>
              <p class="small mb-0 text-dark">
                <span class="text-primary font-weight-bold">Client:</span>
                <span class="text-primary font-italic">Order Owner</span>
              </p>
            </div>
            <div class="col-2 d-flex justify-content-center">
              <a href="{{url_for('BP_admin.order_id', id='01')}}" class="btn btn-outline-dark border-0 details-btn">
                <i class="fas fa-chevron-right"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-6">
        <div class="card card-body shadow bg-light border-0 my-2">
          <div class="row d-flex align-items-center">
            <div class="col-10">
              <h5>Order ID: 00001111</h5>
              <p class="small text-muted mb-1">
                <span class="font-weight-bold">Placed On:</span>
                <span class="font-italic">Order Date</span>
              </p>
              <p class="small mb-0 text-dark">
                <span class="text-primary font-weight-bold">Client:</span>
                <span class="text-primary font-italic">Order Owner</span>
              </p>
            </div>
            <div class="col-2 d-flex justify-content-center">
              <a href="{{url_for('BP_admin.order_id', id='01')}}" class="btn btn-outline-dark border-0 details-btn">
                <i class="fas fa-chevron-right"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-6">
        <div class="card card-body shadow bg-light border-0 my-2">
          <div class="row d-flex align-items-center">
            <div class="col-10">
              <h5>Order ID: 00001111</h5>
              <p class="small text-muted mb-1">
                <span class="font-weight-bold">Placed On:</span>
                <span class="font-italic">Order Date</span>
              </p>
              <p class="small mb-0 text-dark">
                <span class="text-primary font-weight-bold">Client:</span>
                <span class="text-primary font-italic">Order Owner</span>
              </p>
            </div>
            <div class="col-2 d-flex justify-content-center">
              <a href="{{url_for('BP_admin.order_id', id='01')}}" class="btn btn-outline-dark border-0 details-btn">
                <i class="fas fa-chevron-right"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock admin_content %}

{% block page_script %}
<!-- <script src="{{url_for('BP_admin.static', filename='js/orders.js')}}"></script> -->
{% endblock %}

app/BP_admin/templates/test-json.html
{% extends 'admin.layout.html' %}
{% set active='reviews' %}

{% block admin_content %}
<div class="container mt-3">
    <p class="h3 text-white">This is how you disable a button in Jinja</p>
    <button class="btn btn-warning btn-lg shadow" {% if disable %} disabled {% endif %}>Example</button>
</div>
{% endblock admin_content %}

{% block page_script %}
<!-- <script src="{{url_for('BP_admin.static', filename='js/reviews.js')}}"></script> -->
{% endblock %}